server:
  port: 9000

spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.68.231/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: tys87198312
  freemarker:
    cache: false



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml




